# -*- coding: utf-8 -*-
"""DataTypeandVariable.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NPeuJ67Jgl7pT4LbyWyVITT1Carm8s_3

Understanding the data type we'll work in python


---
"""

#integer

x=5
y=1/3
print(type(x))
print(type(y))


isinstance("A",str)

#float

x=5.55
y=1/3
print(type(x))
print(type(y))

20>30
30>20

x="HELLO"
y=x
y=y.lower()
print(x)
print(y)

#List
x=[1,2,3]
y=x           #It affects to the list of X too because list is mutable.
y.append(4)   #Adding to the list of Y
print(x)
print(y)

#But if we applied copy it doesn't happen
x=[1,2,3]
y=x.copy()    # This sets Y set separate from list X.
y.append(4)
print(x)
print(y)

#List can be altered as it is mutable, they are hetrogeneous
#can hold value of different types.

my_list=["Hey",1,"go",2,"Butwal"]
print(my_list)

#Takes everycharacter within list as a different item for list
what=list("What is going on ?")
print(what)

#We remove first matching item from list like:
my_list.remove(2)
print(my_list)

#Immutable Data Types : Tuples and Strings
# Values can't be changed

my_tup=(1,2,3)
print(my_tup)

lest=[1,2,3,4,5]
tup=tuple(lest)
print(tup)

print(tup[3])

#Strings

my_str="Hello World"
print(my_str[1])
print(my_str[3:7])
print(my_str.count("W"))  #Number of times the word "W" repeated