# -*- coding: utf-8 -*-
"""DictionaryAndSet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xPwW20M82y7ekt8ntqYnHVjPUgzf3KhC
"""

# List is searched throughout to find the value. So it could take alot of time.

list=[1,2,3,4,5,6]
3 in list

# In Dictionary, it saves processing time.

dict={"Name":"Vaibhav","Class":"Master","Location":"Sydney"}
print(dict)

#Adding new key and value in dictionary

dict["Age"]=8
print(dict)

#deleting value in dictionary
del dict["Class"]
print(dict)

#checking key-item existence in dictionary
"Name" in dict
#print(dict["Name"])

# Checking keys list in Dictionary
dict.keys()

# Checking value list in Dictionary
dict.values()

# Checking key,value list in Dictionary
dict.items()



"""Entering a table in Dictionary
--

Name     | Course          |  City
---
Vaibhav  | Data Analytics   | Sydney
---
Arjun     | Management     |   London
---
Raj      | Hotel Management |  Nepal





"""

Study = {"Name":["Vaibhav","Arjun","Raj"],
         "Course":["Data Analytics","Management","Hotel Management"],
         "Location":["Syndey","London","Nepal"]}

print(Study.keys())
print(Study.values())
print(Study.items())

"""Set are unordered, mutable collection of immutable objects that cannot contain duplicate data."""

set={1,2,3,4,5}
print(set)

set.add(8)
print(set)
set.remove(5)
print(set)

"""Set can be used for intersecting and uniting values just like in math."""

set1={1,2,4,8}
set2={1,2,5,10}

print(set1.union(set2)) #union of two set
print(set1.intersection(set2))  #intersection of two set
print(set1.difference(set2))    #difference of set1 with respect to set2

print(set1.difference(set2))    #difference of set1 with respect to set2
print(set2.difference(set1))    #difference of set2 with respect to set1
# set value is printed in random as it does not have fixed order.