# -*- coding: utf-8 -*-
"""ExploringDataFrame.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ql0N1uswkaYCDvjjLpgX3FPwkbmGxbnP
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

dataset=pd.read_csv("products.csv")

dataset.shape #checking dimensions    #Rows, Columns

print(dataset.head(5))  #Gives 5 first rows from the dataset including the field name

"""print(dataset.tail(5))  #Gives off the last 5 rows"""

dataset.index=dataset["Index"]   #Sets the column "Index" as the index for the dataset
del dataset["Index"]             #deletes the "Index" column from the dataset

print(dataset.head(5))

dataset.columns

dataset.describe()

dataset.info()

import numpy as np
np.mean(dataset,axis=0)   #Get mean of each numeric value