# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tKfSCBpU4jAOxRNta6tgyBM-t-xPAHvK

#Python Arithmetic
"""

#Addition
10+5

#Subtraction
10-5

#Division
10/3

#Multiplication
10*3

# Floor Division
10//3

#For exponentiation(Power)
2**3

##Arithmetic Sequence so first ** then (/ and *)depends on which comes first and then + and -
2**3/2*3+4-5

#So does BODMAS rule
((2**5)-16)/2

#Modulus is by using %
100 % 6

"""#Math library in python

"""

import math #math library

# prompt:
print(math.log(2.71) ) #takes natural logarithm of the argument

print(math.log(100,10) )  # take log base 10 of 100

print(math.exp(10))   #Math library to print the exponential of argument 10

print(math.sqrt(64))  # to print the square root of number

print(abs(-45))

print(math.pi)

"""Round off Function in python"""

print(round(232.342))

print(round(232.665))

print(round(232.347,2))   # round of to two decimal points

#Floor function
print(math.floor(2.8)) #takes down to least whole number
print(math.ceil(2.4) )   #Takes up to nearest whole number