# -*- coding: utf-8 -*-
"""Python_ListComprehension.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R7VHaVTEeL9ejh9MUY7jXq3yejsZI28b
"""

my_list=[]

for num in range(1,101):
  my_list.append(num)

print(my_list)

#List Comprehension

list_2=[num for num in range(1,101)]
print(list_2)

even_num=[num for num in range(1,101) if num%2==0]
print(even_num)

#Combining character of two different string through comprehension
combined=[a+b for a in "life" for b in "study"]
print(combined)

nested=[letters[1] for letters in [a+b for a in "life" for b in "study"] ]    #Printing letter in index 1 from output gained from [a+b for a in "life" for b in "study"]
print(nested)

combined=[a+b for a in "life" for b in "study"]
nested=[letters[1] for letters in combined]

print(nested)

#Dictionary Comprehension
words=["Life","is","Beautiful"]
print(words)
word_length_dict={}

for word in words:
  word_length_dict[word]=len(word)

print(word_length_dict)

words=["Life","is","Beautiful"]
len_dict={word:len(word) for word in words}
print(len_dict)

word=["Life","is","Beautiful"]
length=[4,2,9]
pair=zip(word,length)

for item in pair:
  print(item)

word=["Life","is","Beautiful"]
length=[4,2,9]

pair=zip(word,length)
pair_dict={key:value for (key,value) in pair}
print(pair_dict)