# -*- coding: utf-8 -*-
"""ReadingAndWritingData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v-rs6TMYhkA2OzHA9Fjsbu1OPSueecnf

## Reading and Writing Data
"""

#Checking file location where python is running
import os
os.getcwd()   #cwd - Checking work directory

os.listdir("/content/sample_data")    ## checking directory content

#Before reading data from CSV Files we import in cloud google colab
from google.colab import files
uploaded=files.upload()

#Importing pandas library to read csv file
import pandas as pd
df=pd.read_csv("products.csv")
df.head()

df.index=df["Index"]    ##Setting "Index" as main index point of the given df
del df["Index"]     #Removing the extra index
df.head()